### PR TITLE
Updated README for PyDy 0.3.0. Fixes #63.

### LINKED ISSUE #63: Explain the different releases in the README.

### PR DESCRIPTION
**Pull request by moorepants**
@jcrist Please review and merge.

### CODE REVIEW

**Comment by jcrist** [comment]
It appears I don't have write access to this repo?

**Comment by moorepants** [comment]
Will fix that.

**Comment by moorepants** [comment]
I made you an owner of the PyDy org. You have full permissions now.

**Comment by jcrist** [comment]
Thanks. I'll look through the rest of these later tonight.

**Pull request merged**
